apiVersion: v1
kind: Service
metadata:
  name: {{ include "eb-app.name" . }}
  labels:
    {{- include "eb-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "eb-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
